"""Add link_token and link_expiration columns to Customer

Revision ID: 69b9958cf1cb
Revises: 8718f3476eca
Create Date: 2024-09-15 20:41:01.751447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69b9958cf1cb'
down_revision: Union[str, None] = '8718f3476eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('link_token', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('link_expiration', sa.Boolean(), nullable=True, default=False))
    op.create_index(op.f('ix_customers_link_token'), 'customers', ['link_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_link_token'), table_name='customers')
    op.drop_column('customers', 'link_expiration')
    op.drop_column('customers', 'link_token')