"""Update Customer table for registered

Revision ID: 3431f975f849
Revises: 1664b4be5a57
Create Date: 2024-10-13 07:53:42.018535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3431f975f849'
down_revision: Union[str, None] = '1664b4be5a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column for combined Aadhaar photos
    op.add_column('customers', sa.Column('registered', sa.Boolean(), nullable=True, server_default='false'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('customers', 'registered')
   