"""Update Customer table for combined Aadhaar photos

Revision ID: 6ba5806ab807
Revises: e18d25e1bd88
Create Date: 2024-10-12 16:17:56.198160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ba5806ab807'
down_revision: Union[str, None] = 'e18d25e1bd88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column for combined Aadhaar photos
    op.add_column('customers', sa.Column('photo_adhaar_combined', sa.String(), nullable=True))

    # Drop old separate Aadhaar photo columns
    op.drop_column('customers', 'photo_adhaar_front')
    op.drop_column('customers', 'photo_adhaar_back')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the separate Aadhaar photo columns
    op.add_column('customers', sa.Column('photo_adhaar_front', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('photo_adhaar_back', sa.String(), nullable=True))

    # Drop the combined Aadhaar photo column
    op.drop_column('customers', 'photo_adhaar_combined')
    # ### end Alembic commands ###