"""Update Customer table for delivery photo

Revision ID: 8805a1a3c92c
Revises: 3431f975f849
Create Date: 2024-10-13 08:12:11.874924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8805a1a3c92c'
down_revision: Union[str, None] = '3431f975f849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column for combined Aadhaar photos
    op.add_column('customers', sa.Column('delivery_photo', sa.String(), nullable=True))




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('customers', 'delivery_photo')
