"""Update Customer table and add link and customer_sign_copy

Revision ID: a95cbf7416f1
Revises: 8805a1a3c92c
Create Date: 2024-10-22 21:40:41.075392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a95cbf7416f1'
down_revision: Union[str, None] = '8805a1a3c92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column for combined Aadhaar photos
    op.add_column('customers', sa.Column('link', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('customer_sign_copy', sa.String(), nullable=True))




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('customers', 'customer_sign_copy')
    op.drop_column('customers', 'link')
