"""Added branch_id to finance_options

Revision ID: d4bb39f271e9
Revises: ccf92cf8aa3b
Create Date: 2024-09-19 15:14:18.738174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4bb39f271e9'
down_revision: Union[str, None] = 'ccf92cf8aa3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_options', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'finance_options', 'branches', ['branch_id'], ['branch_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_options', type_='foreignkey')
    op.drop_column('finance_options', 'branch_id')
    # ### end Alembic commands ###